spring.application.name=proto
spring.datasource.url=jdbc:postgresql://localhost:5432/checklistdatabase
spring.datasource.username=postgres
spring.datasource.password=star
spring.datasource.driver-class-name=org.postgresql.Driver
